sudo: false
dist: trusty
language: perl
perl:
- '5.30'
- '5.14'
before_install:
- git config --global user.name "TravisCI"
install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- cpanm --quiet --notest Test::Kwalitee
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest Dist::Zilla::App::Command::cover
- dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
- dzil listdeps --author | cpanm --quiet --notest --skip-satisfied
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c
  HARNESS_TIMER=1
- dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied
script:
- dzil smoke --release --author 2> /dev/null
after_success:
- dzil cover -outputdir cover_db -report coveralls
notifications:
  slack:
    secure: ZQxH5U+sxuCdGyq+VUiv/THPgCmJ/CuQo4tJ4Q3qidB7gm+SDz8r/dD9VJ5Isyb0iNvjWVBJdHppWQvQUcZOh4fb7OIoM48G5FsZuHl0mvyzuXabUhXsMz1iT4UUVdtARgOHF76thIKfnRZZwK7wdohFPqRZ/35+LUxO+lrPAjg=
